const mongoose=require('mongoose')
const prefernceSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        unique:true,
        required:true
    },
    categories:{
        type:[String],
        default:["general"]
    },
    frequency:{
        type:String,
        enum:["instant","daily"],
        default:"instant"
    },
    realTimeEnabled:{
        type:Boolean,
        default:true
    },
    emailEnabled:{
        type:Boolean,
        default:true
    },
    keywords:{
        type:[String],
        default:[]
    },
    language:{
        type:String,
        default:"en"
    },
    country:{
        type:String,
        default:"in"
    },
    
},{timestamps:true})
module.exports=mongoose.model("Preference",prefernceSchema,"test1")
